name: Vankaka
favicon: null
layout_spectrum: 0.77597
typography_spectrum: 0.51138
title: Thiết kế
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddc7b7'
    - '#ffffff'
    - '#8d7a6b'
    - '#1c1d1c'
    - '#589f3f'
  brandStrength: 0.3996726463083178
  lightness: 0.4375
  saturation: 0.6651367517188191
  rhythmicContrast: 0
purpose: []
