name: Vankaka
favicon: null
layout_spectrum: 1
typography_spectrum: 0.01284
title: Thiết kế website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddc7b7'
    - '#ffffff'
    - '#8d7a6b'
    - '#1c1d1c'
    - '#589f3f'
  brandStrength: 0
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
